version: "3"

volumes:
  vendor:
  datashare:

services:
  vue-web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "8080:80"
    tty: true
    volumes:
      - .:/work_vue
      - datashare:/datashare